In [2]:
pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [7]:
!pip install numpy==1.24.4

Defaulting to user installation because normal site-packages is not writeable

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\Admin\\AppData\\Roaming\\Python\\Python311\\site-packages\\~umpy.libs\\libscipy_openblas64_-c16e4918366c6bc1f1cd71e28ca36fc0.dll'
Check the permissions.




  Obtaining dependency information for numpy==1.24.4 from https://files.pythonhosted.org/packages/d8/ec/ebef2f7d7c28503f958f0f8b992e7ce606fb74f9e891199329d5f5f87404/numpy-1.24.4-cp311-cp311-win_amd64.whl.metadata
   ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.8 MB 217.9 kB/s eta 0:01:08
   ---------------------------------------- 0.1/14.8 MB 375.8 kB/s eta 0:00:40
    --------------------------------------- 0.3/14.8 MB 1.5 MB/s eta 0:00:10
   --- ------------------------------------ 1.2/14.8 MB 5.3 MB/s eta 0:00:03
   ---- ----------------------------------- 1.7/14.8 MB 6.2 MB/s eta 0:00:03
   ------- -------------------------------- 2.9/14.8 MB 9.2 MB/s eta 0:00:02
   ----------- ---------------------------- 4.1/14.8 MB 11.5 MB/s eta 0:00:01
   ------------- ---------------

In [1]:
import tensorflow as tf
print(tf.__version__)
import numpy as np
print(np.__version__)

2.19.0
1.24.4


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255, x_test/255

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [8]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)),
                                                          tf.keras.layers.Dense(128, activation='relu'),
                                                          tf.keras.layers.Dropout(0,2),
                                                          tf.keras.layers.Dense(10)])

C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [9]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.40662116,  0.27641   ,  0.34386113,  0.00929728, -0.6309982 ,
        -0.12879623, -0.03732962,  0.13903597, -0.49021736, -0.61777943]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.07334162, 0.14520688, 0.15533912, 0.11116847, 0.05860097,
        0.09682965, 0.10610402, 0.12656872, 0.06745981, 0.05938075]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1],predictions).numpy()

2.334802

In [14]:
model.compile(optimizer='adam',loss=loss_fn, metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8753 - loss: 0.4394
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9650 - loss: 0.1208
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9754 - loss: 0.0814
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9835 - loss: 0.0570
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9863 - loss: 0.0445


In [16]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9778 - loss: 0.0761


[0.07610706984996796, 0.9778000116348267]

In [18]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])
probability_model(x_test[:3])

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[7.80379494e-08, 1.05678204e-07, 9.86041050e-05, 7.70213199e-04,
        8.90900478e-11, 3.43238952e-07, 9.51474576e-12, 9.99076366e-01,
        7.18145611e-06, 4.70805971e-05],
       [1.00262554e-09, 1.60450163e-05, 9.99962091e-01, 9.23513142e-08,
        1.26580414e-13, 2.45852129e-06, 6.55998804e-07, 1.34695211e-15,
        1.86496436e-05, 9.34867526e-13],
       [8.80102789e-07, 9.99479115e-01, 1.76790825e-04, 2.87206640e-05,
        8.58379371e-06, 4.58046497e-06, 1.85973640e-05, 1.68981118e-04,
        1.13418799e-04, 4.27793793e-07]], dtype=float32)>